export const GET_PROFILE_FORM_DATA = ({firstName,lastName,designation,qualification,positionType,emailId,phoneNumber,avatar,dateOfBirth,dateOfJoin,status}) => [
    {
        id: `firstName`,
        label: ``,
        leftSideLabel: `First Name`,
        leftSideLabelVariant: `subtitle1`,
        leftSideLabelSx: {
            fontWeight: 550,
            fontSize: `16px`,
            minWidth: `95px`,
        },
        fullWidth: true,
        value: firstName,
        type: `input`,
        size: `small`,
        gridColumn: `1 / 9`,
        gridRow: `1`,
    },
    {
        id: `firstName`,
        label: ``,
        value: `Name`,
        // type: `input`,
        gridColumn: `9 / 13`,
        gridRow: `1 / 4`,
    },
    {
        id: `lastName`,
        label: ``,
        leftSideLabel: `Last Name`,
        leftSideLabelVariant: `subtitle1`,
        leftSideLabelSx: {
            fontWeight: 550,
            fontSize: `16px`,
            minWidth: `95px`,
        },
        fullWidth: true,
        value: lastName,
        type: `input`,
        size: `small`,
        gridColumn: `1 / 9`,
        gridRow: `2 / 3`,
    },
    {
        id: `email`,
        label: ``,
        leftSideLabel: `Email Id`,
        leftSideLabelVariant: `subtitle1`,
        leftSideLabelSx: {
            fontWeight: 550,
            fontSize: `16px`,
            minWidth: `95px`,
        },
        fullWidth: true,
        value: emailId,
        type: `input`,
        size: `small`,
        gridColumn: `1 / 7`,
        gridRow: `4 / 5`,
    },
    {
        id: `phoneNumber`,
        label: ``,
        leftSideLabel: `Phone Number`,
        leftSideLabelVariant: `subtitle1`,
        leftSideLabelSx: {
            fontWeight: 550,
            fontSize: `16px`,
            minWidth: `fit-content`,
        },
        fullWidth: true,
        value: phoneNumber,
        type: `input`,
        size: `small`,
        gridColumn: `7 / 13`,
        gridRow: `4 / 5`,
    },
    {
        id: `dataOfJoin`,
        label: ``,
        leftSideLabel: `Date of Join`,
        leftSideLabelVariant: `subtitle1`,
        leftSideLabelSx: {
            fontWeight: 550,
            fontSize: `16px`,
            minWidth: `95px`,
        },
        fullWidth: true,
        value: dateOfJoin,
        type: `input`,
        size: `small`,
        gridColumn: `1 / 7`,
        gridRow: `6 / 7`,
    },
    {
        id: `dateOfBirth`,
        label: ``,
        leftSideLabel: `Date of Birth`,
        leftSideLabelVariant: `subtitle1`,
        leftSideLabelSx: {
            fontWeight: 550,
            fontSize: `16px`,
            minWidth: `fit-content`,
        },
        fullWidth: true,
        value: dateOfBirth,
        type: `input`,
        size: `small`,
        gridColumn: `7 / 13`,
        gridRow: `6 / 7`,
    },
    {
        id: `designation`,
        label: ``,
        leftSideLabel: `Designation`,
        leftSideLabelVariant: `subtitle1`,
        leftSideLabelSx: {
            fontWeight: 550,
            fontSize: `16px`,
            minWidth: `95px`,
        },
        fullWidth: true,
        value: designation,
        type: `input`,
        size: `small`,
        gridColumn: `1 / 6`,
        gridRow: `3 / 4`,
    },
    {
        id: `qualification`,
        label: ``,
        leftSideLabel: `Qualification`,
        leftSideLabelVariant: `subtitle1`,
        leftSideLabelSx: {
            fontWeight: 550,
            fontSize: `16px`,
            minWidth: `fit-content`,
        },
        fullWidth: true,
        value: qualification,
        type: `input`,
        size: `small`,
        gridColumn: `5 / 10`,
        gridRow: `5 / 6`,
    },
    {
        id: `status`,
        label: ``,
        leftSideLabel: `Status`,
        leftSideLabelVariant: `subtitle1`,
        leftSideLabelSx: {
            fontWeight: 550,
            fontSize: `16px`,
            minWidth: `95px`,
        },
        fullWidth: true,
        value: status,
        type: `input`,
        size: `small`,
        gridColumn: `1 / 5`,
        gridRow: `5 / 6`,
    },
    {
        id: `age`,
        label: ``,
        leftSideLabel: `Age`,
        leftSideLabelVariant: `subtitle1`,
        leftSideLabelSx: {
            fontWeight: 550,
            fontSize: `16px`,
            minWidth: `fit-content`,
        },
        fullWidth: true,
        value: `20`,
        type: `input`,
        size: `small`,
        gridColumn: `10 / 13`,
        gridRow: `5 / 6`,
    },
    {
        id: `type`,
        label: ``,
        leftSideLabel: `Type`,
        leftSideLabelVariant: `subtitle1`,
        leftSideLabelSx: {
            fontWeight: 550,
            fontSize: `16px`,
            minWidth: `fit-content`,
        },
        fullWidth: true,
        value: positionType,
        type: `input`,
        size: `small`,
        gridColumn: `6 / 9`,
        gridRow: `3 / 4`,
    },
]