export const GET_PROFILE_FORM_DATA = () => [
    {
        id: `firstName`,
        label: ``,
        leftSideLabel: `First Name`,
        leftSideLabelVariant: `subtitle1`,
        leftSideLabelSx: {
            fontWeight: 550,
            fontSize: `16px`,
            minWidth: `95px`,
        },
        fullWidth: true,
        value: `Name`,
        type: `input`,
        gridColumn: `1 / 9`,
        gridRow: `1`,
    },
    {
        id: `firstName`,
        label: ``,
        value: `Name`,
        // type: `input`,
        gridColumn: `9 / 13`,
        gridRow: `1 / 4`,
    },
    {
        id: `lastName`,
        label: ``,
        leftSideLabel: `Last Name`,
        leftSideLabelVariant: `subtitle1`,
        leftSideLabelSx: {
            fontWeight: 550,
            fontSize: `16px`,
            minWidth: `95px`,
        },
        fullWidth: true,
        value: `Name`,
        type: `input`,
        gridColumn: `1 / 9`,
        gridRow: `2 / 3`,
    },
    {
        id: `email`,
        label: ``,
        leftSideLabel: `Email Id`,
        leftSideLabelVariant: `subtitle1`,
        leftSideLabelSx: {
            fontWeight: 550,
            fontSize: `16px`,
            minWidth: `95px`,
        },
        fullWidth: true,
        value: `Email`,
        type: `input`,
        gridColumn: `1 / 8`,
        gridRow: `4 / 5`,
    },
    {
        id: `phoneNumber`,
        label: ``,
        leftSideLabel: `Phone Number`,
        leftSideLabelVariant: `subtitle1`,
        leftSideLabelSx: {
            fontWeight: 550,
            fontSize: `16px`,
            minWidth: `fit-content`,
        },
        fullWidth: true,
        value: `Phone Number`,
        type: `input`,
        gridColumn: `8 / 13`,
        gridRow: `4 / 5`,
    },
    {
        id: `designation`,
        label: ``,
        leftSideLabel: `Designation`,
        leftSideLabelVariant: `subtitle1`,
        leftSideLabelSx: {
            fontWeight: 550,
            fontSize: `16px`,
            minWidth: `95px`,
        },
        fullWidth: true,
        value: `Designation`,
        type: `input`,
        gridColumn: `1 / 6`,
        gridRow: `3 / 4`,
    },
    {
        id: `qualification`,
        label: ``,
        leftSideLabel: `Qualification`,
        leftSideLabelVariant: `subtitle1`,
        leftSideLabelSx: {
            fontWeight: 550,
            fontSize: `16px`,
            minWidth: `fit-content`,
        },
        fullWidth: true,
        value: `Qualification`,
        type: `input`,
        gridColumn: `5 / 10`,
        gridRow: `5 / 6`,
    },
    {
        id: `status`,
        label: ``,
        leftSideLabel: `Status`,
        leftSideLabelVariant: `subtitle1`,
        leftSideLabelSx: {
            fontWeight: 550,
            fontSize: `16px`,
            minWidth: `95px`,
        },
        fullWidth: true,
        value: `Status`,
        type: `input`,
        gridColumn: `1 / 5`,
        gridRow: `5 / 6`,
    },
    {
        id: `age`,
        label: ``,
        leftSideLabel: `Age`,
        leftSideLabelVariant: `subtitle1`,
        leftSideLabelSx: {
            fontWeight: 550,
            fontSize: `16px`,
            minWidth: `fit-content`,
        },
        fullWidth: true,
        value: `20`,
        type: `input`,
        gridColumn: `10 / 13`,
        gridRow: `5 / 6`,
    },
    {
        id: `type`,
        label: ``,
        leftSideLabel: `Type`,
        leftSideLabelVariant: `subtitle1`,
        leftSideLabelSx: {
            fontWeight: 550,
            fontSize: `16px`,
            minWidth: `fit-content`,
        },
        fullWidth: true,
        value: `Type`,
        type: `input`,
        gridColumn: `6 / 9`,
        gridRow: `3 / 4`,
    },
]