export const API_RESPONSES = "API_RESPONSES";

export const LOGIN_USER = "LOGIN_USER";
export const GET_USER_INFO = 'GET_USER_INFO';
export const LOGOUT_USER = 'LOGOUT_USER';

export const LOADER_START = "LOADER_START";
export const LOADER_END = "LOADER_END";

export const APPLY_TO_LEAVE = "APPLY_TO_LEAVE";
export const GET_LEAVE_LIST = "GET_LEAVE_LIST";
export const GET_LEAVE_INFO = "GET_LEAVE_INFO";
export const CANCEL_LEAVE = "CANCEL_LEAVE";
export const EDIT_LEAVE = "EDIT_LEAVE";
export const REJECT_LEAVE = "REJECT_LEAVE";
export const APPROVE_LEAVE = "APPROVE_LEAVE";

export const UPLOAD_IMAGE_PROFILE = "UPLOAD_IMAGE_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";

export const GET_USERS_LIST = "GET_USERS_LIST";
export const GET_EMPLOYEE_INFO = "GET_EMPLOYEE_INFO";