export const EMPLOYEE_TABLE = () => [
    {
        id: `index`,
        label: `Index`,
        type: `number`,
        sortable: true,
        searchable: true,
    },
    {
        id: `firstName`,
        label: `FirstName`,
        type: `string`,
        sortable: true,
        searchable: true,
    },
    {
        id: `lastName`,
        label: `LastName`,
        type: `string`,
        sortable: true,
        searchable: true,
    },
    {
        id: `designation`,
        label: `Designation`,
        type: `string`,
        sortable: true,
        searchable: true,
    },
    {
        id: `qualification`,
        label: `Qualification`,
        type: `string`,
        sortable: true,
        searchable: true,
    },
    {
        id: `emailId`,
        label: `Email Id`,
        type: `string`,
        sortable: true,
        searchable: true,
    },
    {
        id: `phoneNumber`,
        label: `Phone Number`,
        type: `string`,
        sortable: true,
        searchable: true,
    },
    {
        id: `dateOfBirth`,
        label: `Date ff Birth`,
        type: `date`,
        sortable: true,
        searchable: true,
    },
    {
        id: `dateOfJoin`,
        label: `Date of Join`,
        type: `date`,
        sortable: true,
        searchable: true,
    },
    {
        id: `status`,
        label: `Status`,
        type: `chip`,
        sortable: true,
        searchable: true,
    },
    {
        id: `action`,
        label: `Action`,
        type: `button`,
        sortable: true,
        searchable: true,
    },
];